config/routes.rb
Rails.application.routes.draw do

  get 'users/index'
  get 'users/show'
  devise_for :users

  put "/courses/:id/add" => "courses#add_student"
  # redirect to instructors 
  # devise_scope :user do
  #   authenticated :user do
  #     root 'instructors#index', as: :authenticated_root
  #   end
  
  #   unauthenticated do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  #   end
  # end  
  root 'homes#index'

  resources :homes
  resources :courses
  resources :students
  resources :instructors


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :instructor, class_name: 'User', foreign_key: 'instructor_id'

    def self.search(search)
        if search
          where('name LIKE ?', "%#{search}%")
        else
          all
        end
      end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  

  has_many :courses, foreign_key: "instructor_id", dependent: :destroy

  enum role: [:user, :student, :instructor]
    after_initialize :set_default_role, :if => :new_record?
    def set_default_role
    self.role ||= :user
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!, :except  [:index]

    # def after_sign_in_path_for(resource)
    #     if resource.instructor?
    #         instructor_path(current_user.id)
    #     else
    #         student_path(current_user.id)
    #     end
    # end


    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_type])
            devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :user_type])
            devise_parameter_sanitizer.permit(:account_update, keys: [:name, :user_type])
      end

      



end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.search(params[:search])
  end

  def show
      @course = Course.find(params[:id])
  end

  def new 
    @course = Course.new

  end

  def create
    
    if current_user.user_type
      @course = Course.create(course_params)
      @course.instructor_id = current_user.id  
      @course.new_course = true 
      @course.save

      redirect_to  @course

    else
      redirect_to  user_path(current_user)
    end
    
    
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    course = Course.find(params[:id])
    course.update(course_params) 
    redirect_to course
  end

  def add_student
    @course = Course.find(params[:id])

    unless current_user.user_type 
      @course.students << current_user.id
      @course.save
      redirect_to courses_path
    else
      redirect_to courses_path
    end
    
  end

  def destroy
    course = Course.find(params[:id])
    course.destroy
    redirect_to courses_path
  end

  private

  def course_params
  params.require(:course).permit(:name, :field, :start, :end, :img, :desc, :instructor_id)

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
   # @user = User.find_by(id: params[:id])
   @user = User.find(params[:id])
  @courses = @user.courses
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
<div class="card shadow p-3 mb-5 bg-white rounded">
  <div class="form-row">
    <div class="col">
    <%= f.label :name %>
     <%= f.text_field :name ,class:"form-control",placeholder:"Course Name"%>
    </div>
    <div class="col">
    <%= f.label :field %>
  <%= f.text_field :field ,class:"form-control",placeholder:"Course Field"%> 
    
    </div>
  </div>
   <div class="form-row">
    <div class="col">
     <%= f.label :start %>
   <%= f.datetime_field :start ,class:"form-control",placeholder:"Start DateTime"%>
    </div>
    <div class="col">
  <%= f.label :end %>
 <%= f.datetime_field :end ,class:"form-control",placeholder:"End DateTime"%> 
    </div>
  </div>
  <div class="form-row">
    <div class="col">
   <%= f.label :img %>
    <%= f.text_field :img ,class:"form-control",placeholder:"Image Url"%>
    </div>
    
  </div>
<div class="form-row">
    <div class="col">
   <%= f.label :desc %>
   <%= f.text_area :desc,class:"form-control", id:"exampleFormControlTextarea1", rows:"3",placeholder:"Description"%>
    </div>
    
  </div>
  <div class="des" >
  <%= f.label :instructor %>
    <%= f.text_field :instructor_id, value:current_user.id  %>
</div>
<br>
<%= f.submit "Create New Course",class:"btn btn-dark", onclick: "alert('Course created successfully')"%>

<% end %>
</div>

app/views/courses/edit.html.erb
<h1 class="space d-flex justify-content-center">Edit Course</h1>

<div class="container space"><%= render 'form' %></div>

app/views/courses/index.html.erb
<div class="container-fluid">
<div class="col-9 space">
    <h1>Courses</h1>
    </div>  
        <% if user_signed_in? && current_user.user_type  %>
    <%= link_to 'Add New Course', new_course_path ,class:"btn btn-dark"%>
    <% end %>
<div class="row space">
     <div class="col-12">
    <div class="row">

    <% if user_signed_in? && current_user.user_type  %>

      <%  current_user.courses.each do |course| %>
        <div class="col-3">
        <div class="card shadow p-3 mb-5 bg-white rounded">
      <img class="card-img-top" src="<%= course.img %>" height="180" width="150" alt="course img">
            
        <ul class="list-group list-group-flush">
        <li class="list-group-item"><b><%= course.name %></b></li>
            <li class="list-group-item"> <b>Start Date:</b>  <%= course.start %></li>
            <li class="list-group-item"> <b>End Date:</b> <%= course.end %> </li>
        </ul>
        <div class="card-body">
           <a ><%= link_to 'Learn More...', course_path(course), class:"btn btn-dark"%></a>
        </div>
        </div>
        <br>
        </div>
        <% end %>

        <% elsif user_signed_in? && current_user.user_type == false  %>
      <%  @courses.each do |course| %>
      <div class="col-3">
        <div class="card shadow p-3 mb-5 bg-white rounded">
        <img class="card-img-top" src="<%= course.img %>" height="180" width="150" alt="course img">
        <ul class="list-group list-group-flush">
        <li class="list-group-item"> <b><%= course.name %></b></li>
            <li class="list-group-item"> <b>Start Date:</b>  <%= course.start %></li>
            <li class="list-group-item"> <b>End Date:</b> <%= course.end %> </li>

        <% if course.students.include? current_user.id.to_s %>
            <li class="list-group-item"> <b>Joind Course</b></li> 
        <% end%>
        </ul>

        <div class="card-body row">
            <%= link_to 'Learn More...', course_path(course), class:"btn btn-dark"%>  
        </div>
        </div>
        <br>
        </div>
        <% end %>
        
<% else %>
<%  @courses.each do |course| %>
<div class="col-3">
        <div class="card shadow p-3 mb-5 bg-white rounded">
        <img class="card-img-top" src="<%= course.img %>" height="180" width="150" alt="course img">
        <ul class="list-group list-group-flush">
        <li class="list-group-item"> <b><%= course.name %></b></li>
            <li class="list-group-item"> <b>Start Date:</b>  <%= course.start %></li>
            <li class="list-group-item"> <b>End Date:</b> <%= course.end %> </li>
        </ul>
        <div class="card-body row">

            <%= link_to 'Learn More...', course_path(course), class:"btn btn-dark"%>  
        </div>
        </div>
        <br>
        </div>
        <% end %>
<% end %>

</div>
</div>

</div>
</div>

app/views/courses/new.html.erb
<h1 class="space d-flex justify-content-center">Add New Course</h1>
<div class="container space"><%= render partial: 'form' %></div>

app/views/courses/show.html.erb
<div class="container space">
<div class="card shadow p-3 mb-5 bg-white rounded">

  <img class="card-img-top" src="<%= @course.img %>" height="500" alt="Card image cap">
  <div class="card-body">
    <h4 class="card-title"><%= @course.name %></h4>
            <p class="card-text"> <b>Instructor: </b><%= @course.instructor.name %></p>
    <p class="card-text"><b>Description:</b><%= @course.desc %></p>
    <p class="card-text"><small class="text-muted">Start: <%= @course.start %></small> <small class="text-muted">End: <%= @course.end %></small></p>
<% if user_signed_in? && current_user.user_type  %>
   <a ><%= link_to 'Edit', edit_course_path(@course), class:"btn btn-dark"%></a>
   <a ><%= link_to 'Delete', course_path(@course),method: :delete , class:"btn btn-dark" , data: {confirm: "Are you sure?"}%></a>
   <% elsif  user_signed_in? && !current_user.user_type  %>
   
            <% if @course.students.include? current_user.id.to_s %>
           <a><%= link_to 'Join this Course',"#{@course.id}/add",method: "put", class:"btn btn-dark disabled"%></a>

       <% else %>
        <a><%= link_to 'Join this Course',"#{@course.id}/add",method: "put", class:"btn btn-dark " , onclick: "alert('You joind #{@course.name} course')" %></a>
        <% end%>

 <% end %>
 
  </div>
</div>
  </div>

app/views/homes/index.html.erb
<div id="carouselExampleInterval" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleInterval" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleInterval" data-slide-to="1"></li>
    <li data-target="#carouselExampleInterval" data-slide-to="2"></li>
    <li data-target="#carouselExampleInterval" data-slide-to="3"></li>

  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="3000">
      <img src="https://slack-imgs.com/?c=1&url=https%3A%2F%2Fwww.true-roots.co.uk%2F_webedit%2Fcached-images%2F10-0-0-0-10000-9888-1152.jpg" class="d-block w-100 " height="700px" alt="image1">
       <div class="carousel-caption d-none d-md-block">
           <h5><b> Follow your Passion</b></h5>
          <p>Passion is energy. Feel the power that comes from focusing on what excites you</p>

           <% if user_signed_in? && !current_user.user_type  %>
         <%= link_to 'Join Now',courses_path,class:"btn btn-dark"  %>
         <%elsif !user_signed_in?%> 
         <%= link_to 'Join Now',new_user_registration_path,class:"btn btn-dark"  %>
         <%end %>
        </div>
    </div>
    <div class="carousel-item" data-interval="3000">
      <img src="https://deneenpottery.com/wp-content/uploads/2018/09/Tips-for-finding-pottery-inspiration-e1536174616517.jpeg" class="d-block w-100"  height="700px" alt="image2">
       <div class="carousel-caption d-none d-md-block">
           <h5><b> Follow your Passion</b></h5>
                    <p>Passion is energy. Feel the power that comes from focusing on what excites you</p>
         <% if user_signed_in? && !current_user.user_type  %>
         <%= link_to 'Join Now',courses_path,class:"btn btn-dark"  %>
         <%elsif !user_signed_in? %> 
         <%= link_to 'Join Now',new_user_registration_path,class:"btn btn-dark"  %>
         <%end %>

        </div>
    </div>
    <div class="carousel-item" data-interval="3000">
      <img src="https://5rd1122q2fb2q9nsj36dtnqz-wpengine.netdna-ssl.com/wp-content/uploads/2015/08/horseriding.jpg" class="d-block w-100" height="700px" alt="image3">
       <div class="carousel-caption d-none d-md-block">
          <h5><b> Follow your Passion</b></h5>
                    <p>Passion is energy. Feel the power that comes from focusing on what excites you</p>
          <% if user_signed_in? && !current_user.user_type  %>
         <%= link_to 'Join Now',courses_path,class:"btn btn-dark"  %>
         <%elsif !user_signed_in? %> 
         <%= link_to 'Join Now',new_user_registration_path,class:"btn btn-dark"  %>
         <%end %>
        </div>
    </div>
     <div class="carousel-item" data-interval="3000">
      <img src="https://slack-imgs.com/?c=1&url=https%3A%2F%2Fleftbankleeds.org.uk%2Fwp-content%2Fuploads%2F2017%2F09%2FKnitting-workshops.jpg" class="d-block w-100" height="700px" alt="image4">
       <div class="carousel-caption d-none d-md-block">
       <h5><b> Follow your Passion</b></h5>
                    <p>Passion is energy. Feel the power that comes from focusing on what excites you</p>
        <% if user_signed_in? && !current_user.user_type  %>
         <%= link_to 'Join Now',courses_path,class:"btn btn-dark"  %>
         <%elsif !user_signed_in? %> 
         <%= link_to 'Join Now',new_user_registration_path,class:"btn btn-dark"  %>
         <%end %>
        </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningTogether</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
 <a class="navbar-brand">

          <img src="https://i.imgur.com/GHGdjR6.png" alt="">
        </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
           <%= link_to 'Home', homes_path, class:"nav-link " %>

     </li>
     <li class="nav-item active">
   <%= link_to 'Courses', courses_path, class:"nav-link " %>
      </li>
    </ul>
    
<%= form_tag(courses_path, method: :get, class:"form-inline my-2 my-lg-0") do %>
  <%= text_field_tag :search, params[:search], placeholder:"Search", class:"form-control mr-sm-2"  %>
  <%= submit_tag 'Search',class:"btn btn-outline-warning my-2 my-sm-0",name:nil %>
<% end %>

        <ul class="navbar-nav">
        
            <%if user_signed_in?%>
            <% if current_user.user_type %>
            <% current_user.instructor!%><%#add role instructor%>
            <%else %>
            <% current_user.student!%> <%#add role student%>
            <% %>
            <%end%>
           
              <li>
              <div class="nav-link ">  <%= link_to current_user.name, edit_user_registration_path , style: 'color:#A9A9A9;'%><i class="fas fa-user"></i></div>

              </li>
              <li>
                <%= link_to 'Log Out',  destroy_user_session_path, class:"nav-link", method: :delete %>
              </li>
            <%else%>
              <li>
                <%=link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
              </li>
              <li>
                <%= link_to 'Log In', new_user_session_path, class:"nav-link" %>
              </li>
            <%end%>
        </ul>
  </div>
</nav>
</div>
    <%= yield %>

  </body>
<!-- Footer -->
<!-- Footer -->
<footer class="page-footer font-small indigo ">

    <!-- Footer Links -->
    <div class="container">

      <!-- Grid row-->
      <div class="row text-center d-flex justify-content-center pt-5 mb-3">

        <!-- Grid column -->
        <div class="col-md-2 mb-3">
          <h6 class="text-uppercase font-weight-bold">
          <%= link_to 'About us', users_index_path ,class:"makeWhite"%>
          </h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 mb-3">
          <h6 class="text-uppercase font-weight-bold">
            <a href="#!" class="makeWhite">Products</a>
          </h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 mb-3">
          <h6 class="text-uppercase font-weight-bold">
            <a href="#!" class="makeWhite">Awards</a>
          </h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 mb-3">
          <h6 class="text-uppercase font-weight-bold">
            <a href="#!" class="makeWhite">Help</a>
          </h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 mb-3">
          <h6 class="text-uppercase font-weight-bold">
            <a href="#!" class="makeWhite">Contact</a>
          </h6>
        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->
      <hr class="rgba-white-light" style="margin: 0 15%;">

      <!-- Grid row-->
      <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">

        <!-- Grid column -->
        <div class="col-md-8 col-12 mt-5">
          <p style="line-height: 1.7rem" >Learn to enjoy every minute of your life. Be happy now. Don't wait for something outside of yourself to make you happy in the future. Think how really precious is the time you have to spend, whether it's at work or with your family. Every minute should be enjoyed and savored.
</p>
        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->
      <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">

      <!-- Grid row-->
      <div class="row pb-3">

        <!-- Grid column -->
        <div class="col-md-12">

          <div class="mb-5 d-flex justify-content-center">

            <!-- Facebook -->
            <a class="fb-ic">
              <i class="fab fa-facebook-f fa-lg white-text mr-4"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic">
              <i class="fab fa-twitter fa-lg white-text mr-4"> </i>
            </a>
            <!-- Google +-->
            <a class="gplus-ic">
              <i class="fab fa-google-plus-g fa-lg white-text mr-4"> </i>
            </a>
            <!--Linkedin -->
            <a class="li-ic">
              <i class="fab fa-linkedin-in fa-lg white-text mr-4"> </i>
            </a>
            <!--Instagram-->
            <a class="ins-ic">
              <i class="fab fa-instagram fa-lg white-text mr-4"> </i>
            </a>
            <!--Pinterest-->
            <a class="pin-ic">
              <i class="fab fa-pinterest fa-lg white-text"> </i>
            </a>
          </div>
             <!-- Copyright -->
    <div class="footer-copyright text-center py-3 ">© 2019 Copyright:Supreme Team
    </div>
    <!-- Copyright -->
        </div>
      </div>
    </div>

  </footer>
  <!-- Footer -->
  </html>

app/views/users/index.html.erb
<div class="container space ">
<div class="card shadow p-3 mb-5 bg-white rounded " ">
<div class="text-center ">
<h1>About us</h1>
<p><b>Team Leader:</b>Mohamed Alhamad</p>
<p><b>Member:</b>Amani Alamri</p>
<p><b>Member:</b>Sarah Abuhaimed</p>
</div>
</div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>